### ISSUE TITLE
common_sensor_launch needs update due to the changes in autoware_pointcloud_preprocessor

### ISSUE THREAD

**Issue by vividf** [tier4/awsim_sensor_kit_launch#21]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

There are several PRs are merged or ready to merge into the autoware universe, which the awsim_sensor_kit_launch also needs updated.

However, unlike the awsim_lab_common_sensor_launch or common_sensor_launch, awsim_common_sensor_launch has its way of writing the launch file. Thus, it would be better that the maintainers change it by themselves. 

Please modify the file based on this PR: 
- https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/104

Issue noticed:
- distortion_corrector_node_param_file is not used in the nebula_node_container.launch.py 

### Purpose

AWSIM can launch successfully after the PR (https://github.com/autowarefoundation/autoware.universe/pull/8469) merged. 

### Possible approaches

Modify the nebula_node_container.launch.py 

### Definition of done

AWSIM can launch successfully after the PR (https://github.com/autowarefoundation/autoware.universe/pull/8469) merged.

**Comment by vividf** [comment]
@SakodaShintaro could you help me implement this since I probably will change the original code too much (because the code is a bit different)

**Comment by SakodaShintaro** [comment]
@vividf 
I created a branch https://github.com/RobotecAI/awsim_sensor_kit_launch/compare/main...SakodaShintaro:awsim_sensor_kit_launch:fix/filter_param.

However, I get an error

```bash
1729647237.7043915 [ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'voxel_grid_downsample_filter' of type 'autoware::pointcloud_preprocessor::VoxelGridDownsampleFilterComponent' in container 'pointcloud_container': Component constructor threw an exception: Statically typed parameter 'input_frame' must be initialized.
```

The similar errors occur also in `logging_simulator` with the sample_sensor_kit.

```
$ ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-rosbag vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit
[INFO] [launch]: All log files can be found below /home/shintarosakoda/.ros/log/2024-10-23-10-52-26-916002-dpc2304005-673089
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/pointcloud_container/glog_component' in container '/pointcloud_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/system/component_state_monitor/component' in container '/system/component_state_monitor/container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/sensing/lidar/top/glog_component' in container '/sensing/lidar/top/pointcloud_preprocessor/pointcloud_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/system/mrm_emergency_stop_operator' in container '/system/mrm_emergency_stop_operator/mrm_emergency_stop_operator_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/system/mrm_comfortable_stop_operator' in container '/system/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/sensing/lidar/right/glog_component' in container '/sensing/lidar/right/pointcloud_preprocessor/pointcloud_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/sensing/lidar/rear/glog_component' in container '/sensing/lidar/rear/pointcloud_preprocessor/pointcloud_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/sensing/lidar/left/glog_component' in container '/sensing/lidar/left/pointcloud_preprocessor/pointcloud_container'
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/map/pointcloud_map_loader' in container '/map/map_container'
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'crop_box_filter_measurement_range' of type 'autoware::pointcloud_preprocessor::CropBoxFilterComponent' in container '/pointcloud_container': Component constructor threw an exception: Statically typed parameter 'max_queue_size' must be initialized.
```

I am still investigating.

**Comment by vividf** [comment]
Thanks for your work.
I close the PR so this issue is not exist anymore :)
